fix(#229): add semi-transparent background on 404 message
kaliacad/mostvisitedarticle pull request #236
Opened 2024-07-27 19:07 UTC by geekananya

## Pull Request

### Description

I made the following changes to prevent 404 notfound page message from being invisible over some backgrounds.

### Changes Made

- Wrapped the text in another div.
- Added Semi-transparent white background
- Added padding

2024-07-29 21:35 UTC, CREDO23 requested changes
@geekananya, It looks good ! Thanks.
Just add the requested changes !

Also, try to apply the opacity to the full page and center text content, or keep the opaque box as is and center it in the screen !

2024-07-29 21:35 UTC, CREDO23 commented on src/pages/NotFound.jsx
> +                    backgroundColor: 'rgb(256, 256,256, 0.3)',
Can you increase once more the opacity, try with 0.45

2024-07-29 21:35 UTC, CREDO23 commented on src/pages/NotFound.jsx
> +                    backgroundColor: 'rgb(256, 256,256, 0.3)',
Please use tailwind classes here @geekananya

2024-07-29 21:35 UTC, CREDO23 commented on src/pages/NotFound.jsx
> +                >
Use tailwind CSS

2024-07-29 21:35 UTC, CREDO23 commented on src/pages/NotFound.jsx
> +                <Button text={'Go to home'} event={handleClick} />
This button is invisible in the page ! Please, make it visible ...

2024-07-30 07:01 UTC, geekananya commented
Hi, @CREDO23, thanks for the review! I will apply the new changes and get back to you.

2024-07-30 19:59 UTC, geekananya commented
@CREDO23, I made the changes as requested, please review the updates and let me know if any modifications are needed.

2024-07-30 22:08 UTC, CREDO23 approved these changes
Thanks for your contribution @geekananya !

2024-07-30 22:08 UTC, merged